routes/web.php
	Route::post('lien-he','HomeController@PostLienhe');
	Route::get('faq-contact','HomeController@getFaqContact')->name('faq-contact');
	Route::post('faq-contact','HomeController@postFaqContact');
	Route::get('bang-gia','HomeController@BangGia')->name('bang-gia');

	Route::get('bang-gia-contact','HomeController@getBaoGiaContact')->name('bang-gia-contact');
	Route::post('bang-gia-contact','HomeController@postBaoGiaContact');
	
	Route::get('bang-gia/{alias}','HomeController@Banggiadetail')->name('bang-gia-detail');
	Route::get('bieu-mau','HomeController@Bieumau')->name('bieu-mau');
	Route::get('bieu-mau/{alias}','HomeController@Bieumaudetails')->name('bieu-mau-detail');
	Route::get('tai-lieu','HomeController@TaiLieu')->name('tai-lieu');
	Route::get('danh-muc-bieu-mau/{id}/{tenloai}','HomeController@CateDanhmucBieumau')->name('danh-muc-bieu-mau');
	Route::get('danh-muc-tai-lieu/{id}/{tenloai}','HomeController@CateDanhmucTaiLieu')->name('danh-muc-tai-lieu');
	Route::get('hoi-dap','HomeController@FAQ')->name('hoi-dap');
	Route::post('tim-kiem-hoi-dap','HomeController@timkiem_hoidap');
	Route::post('tim-kiem-bieu-mau','HomeController@timkiem_bieumau');
	Route::post('tim-kiem','HomeController@timkiem');
	
	Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('user.change-language');

});

Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
Route::get('logout','LoginController@getLogout')->name('getLogout');
Route::post('sign-in','LoginController@postLogin');

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu');

	Route::prefix('admin')->name('admin.')->group(function(){
		Route::get('index','AdminsController@index')->name('index');

		Route::get('add','AdminsController@create')->name('create');
		Route::post('add','AdminsController@store')->name('store');

		Route::get('edit/{id}','AdminsController@edit')->name('edit');
		Route::post('edit/{id}','AdminsController@update')->name('update');

		Route::get('change-password','AdminsController@Getchangepass')->name('changepass.update');
		Route::post('change-password','AdminsController@changepass')->name('postchangepass.update');

		Route::get('delete/{id}','AdminsController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::get('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('slider')->name('slider.')->group(function(){
		Route::get('index','SliderController@index')->name('index');

		Route::get('add','SliderController@create')->name('create');
		Route::post('add','SliderController@store')->name('store');

		Route::get('edit/{id}','SliderController@edit')->name('edit');
		Route::post('edit/{id}','SliderController@update')->name('update');

		Route::get('delete/{id}','SliderController@destroy')->name('destroy');
	});
	Route::prefix('lienhe')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');

		Route::get('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('hoidap')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');

		Route::get('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('nhanxet')->name('nhanxet.')->group(function(){
		Route::get('index','NhanXetController@index')->name('index');

		Route::get('add','NhanXetController@create')->name('create');
		Route::post('add','NhanXetController@store')->name('store');

		Route::get('edit/{id}','NhanXetController@edit')->name('edit');
		Route::post('edit/{id}','NhanXetController@update')->name('update');

		Route::get('delete/{id}','NhanXetController@destroy')->name('destroy');
	});
	Route::prefix('category-file')->name('category-file.')->group(function(){
		Route::get('index','CategoryFileController@index')->name('index');

		Route::get('add','CategoryFileController@create')->name('create');
		Route::post('add','CategoryFileController@store')->name('store');

		Route::get('edit/{id}','CategoryFileController@edit')->name('edit');
		Route::post('edit/{id}','CategoryFileController@update')->name('update');

		Route::get('delete/{id}','CategoryFileController@destroy')->name('destroy');
	});
	Route::prefix('file')->name('file.')->group(function(){
		Route::get('index','FileController@index')->name('index');
		Route::get('link-file','FileController@Linkfile')->name('link-file');

		Route::get('add','FileController@create')->name('create');
		Route::post('add','FileController@store')->name('store');

		Route::get('edit/{id}','FileController@edit')->name('edit');
		Route::post('edit/{id}','FileController@update')->name('update');

		Route::get('delete/{id}','FileController@destroy')->name('destroy');
	});
	Route::prefix('category')->name('category.')->group(function(){
		Route::get('index','CategoryController@index')->name('index');

		Route::get('add','CategoryController@create')->name('create');
		Route::post('add','CategoryController@store')->name('store');

		Route::get('edit/{id}','CategoryController@edit')->name('edit');
		Route::post('edit/{id}','CategoryController@update')->name('update');

		Route::get('delete/{id}','CategoryController@destroy')->name('destroy');
	});
	Route::prefix('news')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');

		Route::get('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('dichvu')->name('dichvu.')->group(function(){
		Route::get('index','ServiceController@index')->name('index');

		Route::get('add','ServiceController@create')->name('create');
		Route::post('add','ServiceController@store')->name('store');

		Route::get('edit/{id}','ServiceController@edit')->name('edit');
		Route::post('edit/{id}','ServiceController@update')->name('update');

		Route::get('delete/{id}','ServiceController@destroy')->name('destroy');
	});
	Route::prefix('banggia')->name('banggia.')->group(function(){
		Route::get('index','ListPriceController@index')->name('index');

		Route::get('add','ListPriceController@create')->name('create');
		Route::post('add','ListPriceController@store')->name('store');

		Route::get('edit/{id}','ListPriceController@edit')->name('edit');
		Route::post('edit/{id}','ListPriceController@update')->name('update');

		Route::get('delete/{id}','ListPriceController@destroy')->name('destroy');
	});
	Route::prefix('gioithieu')->name('introduce.')->group(function(){
		Route::get('index','IntroduceController@index')->name('index');
		Route::post('edit/{id}','IntroduceController@update')->name('update');
	});
	Route::prefix('logo')->name('logo.')->group(function(){
		Route::get('index','LogoController@index')->name('index');
		Route::post('edit/{id}','LogoController@update')->name('update');
	});
	Route::prefix('mangxahoi')->name('mangxahoi.')->group(function(){
		Route::get('index','SocialNetworkController@index')->name('index');
		Route::post('edit/{id}','SocialNetworkController@update')->name('update');
	});
	Route::prefix('googlemap')->name('googlemap.')->group(function(){
		Route::get('index','GoogleMapController@index')->name('index');
		Route::post('edit/{id}','GoogleMapController@update')->name('update');
	});
	Route::prefix('contactus')->name('contactus.')->group(function(){
		Route::get('index','ContactUsController@index')->name('index');
		Route::post('edit/{id}','ContactUsController@update')->name('update');
	});
	Route::prefix('footer')->name('footer.')->group(function(){
		Route::get('index','FooterController@index')->name('index');
		Route::post('edit/{id}','FooterController@update')->name('update');
	});
	Route::prefix('cauhinhkhac')->name('cauhinhkhac.')->group(function(){
		Route::get('index','ConfigurationController@index')->name('index');
		Route::post('edit/{id}','ConfigurationController@update')->name('update');
	});
	Route::prefix('faqcontact')->name('faqcontact.')->group(function(){
		Route::get('index','FAQContactController@index')->name('index');

		Route::get('add','FAQContactController@create')->name('create');
		Route::post('add','FAQContactController@store')->name('store');

		Route::get('edit/{id}','FAQContactController@edit')->name('edit');
		Route::post('edit/{id}','FAQContactController@update')->name('update');

		Route::get('delete/{id}','FAQContactController@destroy')->name('destroy');
	});
	Route::prefix('baogiacontact')->name('baogiacontact.')->group(function(){
		Route::get('index','BaoGiaContactController@index')->name('index');

		Route::get('add','BaoGiaContactController@create')->name('create');
		Route::post('add','BaoGiaContactController@store')->name('store');

		Route::get('edit/{id}','BaoGiaContactController@edit')->name('edit');
		Route::post('edit/{id}','BaoGiaContactController@update')->name('update');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class Category extends Model
{
    protected $table = "c1_dmtt";
    public $timestamp = false;
    public function dbCate()
    {
    	return DB::table('c1_dmtt');
    }
    public function listCate()
    {
    	return $this->dbCate()->orderBy('id','DESC')->get()->toArray();
    }
    public function addCate($data)
    {
    	return $this->dbCate()->insert($data);
    }
    public function editCate($id)
    {
    	return $this->dbCate()->find($id);
    }
    public function updateCate($data,$id)
    {
    	return $this->dbCate()->whereId($id)->update($data);
    }
    public function delCate($data)
    {
    	return $this->dbCate()->delete($data);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Http\Controllers\Controller;
use App\Models\Category;
use DateTime;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $category;
    public function __construct(Category $category)
    {
        $this->category = $category;
    }
    public function CreateCate($request)
    {
        $data = array(
            'parent_id'         => $request->parent_id,
            'name'              => $request->name,
            'alias'             => (empty($request->alias)) ? str_slug($request->name, "-") : $request->alias,
            'language'          => $request->language,
            'created_at'        => new DateTime
        );

        return $data;
    } 
    public function index()
    {
        $data['cate'] = $this->category->listCate();

        return view('admin.modules.category.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.modules.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $data = $this->CreateCate($request);

      $insert = $this->category->addCate($data);
      if ($insert) {
           return redirect()->route('category.index')->with("success",'message.store_required');
      } else {
        return redirect()->back()->with('error','Thêm dữ liệu không thành công. Vui lòng thử lại');
      }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['category'] = $this->category->editCate($id);

        return view('admin.modules.category.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $this->CreateCate($request);

       $update = $this->category->updateCate($data,$id);
       if ( $update) {
            return redirect()->route('category.index')->with("success",'message.update_required');
       }else {
            return redirect()->back()->with('error','Cập nhật dữ liệu không thành công. Vui lòng thử lại');
       }
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $data = $request->chk;
        for ($i=0; $i < count($data); $i++) { 
            $this->category->delCate($data[$i]);
        }

        return redirect()->route('category.index')->with("success",'message.delete_required');
    }
}

resources/views/admin/modules/category/create.blade.php
@extends('admin.master')
@section('title','Thêm Category')
@section('content')
@include('admin.blocks.alert')
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('category.store')}}" method="POST" enctype="multipart/form-data">
            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.add_category')}}</legend>
                    
                    <!-- Basic select -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.parent_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                           <select name="parent_id" class="form-control">
                               <option value="0">ROOT</option>
                           </select>
                        </div>
                    </div>
                    <!-- /basic select -->

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.name_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="name" class="form-control" value="{{old('name')}}" />
                        </div>
                    </div>
                    <!-- /basic text input -->           

                   <!-- Basic text input -->
                    <div class="form-group row" hidden="">
                        <label class="col-form-label col-lg-3">{{trans('template.alias_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="alias" class="form-control" />
                        </div>
                    </div>
                    <!-- /basic text input --> 
                 
                     <!-- Basic ngon ngu input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.language_category')}}</label>
                        <div class="col-lg-3">
                             <select name="language" class="form-control" />
                                <option value="VN">VN</option>
                                <option value="EN">EN</option> 
                           </select>
                        </div>
                    </div>
                    <!-- /basic ngon ngu input -->

                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.cancel')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.create')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/category/edit.blade.php
@extends('admin.master')
@section('title','Edit Category')
@section('content')
@include('admin.blocks.alert')
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('category.update',['id'=> $category->id])}}" method="POST" enctype="multipart/form-data">
            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.edit_category')}}</legend>
                    
                    <!-- Basic select -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.parent_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                           <select name="parent_id" class="form-control">
                               <option value="0">ROOT</option>
                           </select>
                        </div>
                    </div>
                    <!-- /basic select -->

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.name_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="name" class="form-control" value="{{old('name',$category->name)}}" />
                        </div>
                    </div>
                    <!-- /basic text input -->           

                   <!-- Basic text input -->
                    <div class="form-group row" hidden="">
                        <label class="col-form-label col-lg-3">{{trans('template.alias_category')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="alias" class="form-control" />
                        </div>
                    </div>
                    <!-- /basic text input --> 
                 
                     <!-- Basic ngon ngu input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.language_category')}}</label>
                        <div class="col-lg-3">
                             <select name="language" class="form-control" />
                               <option value="VN" {{($category->language == 'VN')? 'selected':''}}>VN</option>
                               <option value="EN" {{($category->language == 'EN')? 'selected':''}}>EN</option>
                           </select>
                        </div>
                    </div>
                    <!-- /basic ngon ngu input -->

                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.cancel')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.update')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/category/index.blade.php
@extends('admin.master') 
@section('title','Danh Sách Category') 
@section('content')
@include('admin.blocks.alert')
<div class="content">

    <!-- Page length options -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{trans('template.list_category')}}</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <a href="{{route('category.create')}}">
                <button type="button" class="btn btn-primary" class="">Thêm danh mục</button>
            </a>
        </div>
        <form action="{{route('category.destroy',['action' => 'delete'])}}" />
            @method('DELETE')
            @csrf
        <table class="table datatable-show-all">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="chkall"  onClick="chkallClick(this);">
                    </th>
                    <th>#</th>
                    <th>Tên danh mục</th>
                    <th>Ngôn ngữ</th>
                    <th>Hoạt động</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
            	@foreach($cate as $item)
                <tr>
                    <td>
                        <input type="checkbox" name="chk[]" value="{{$item->id}}">
                    </td>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$item->name}}</td>
                    <td>
                         @if ($item->language == "VN")
                            <span class="badge badge-primary">VN</span>
                        @elseif ($item->language == "EN")
                            <span class="badge badge-success">EN</span>
                        @endif
                    </td>
                    <td>{{ \Carbon\Carbon::createFromTimeStamp(strtotime($item ->created_at))->diffForHumans() }}</td>
                    <td class="text-center">
                        <a href="{{ route('category.edit',['category' => $item->id]) }}" class="list-icons-item text-primary-600" title="Sửa danh mục"><i class="icon-pencil7"></i></a> &nbsp;
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
            <button type="submit" class="btn btn-danger" onclick="return acceptDelete()" style="margin-left: 10px">{{trans('template.delete')}}</button><br/><br>              
        </form> 
    </div>
    <!-- /page length options -->
</div>
@endsection