routes/web.php
	Route::get('gioi-thieu','HomeController@Introduce')->name('gioi-thieu');
	Route::get('dich-vu','HomeController@Service')->name('dich-vu');
	Route::get('tin-tuc','HomeController@News')->name('tin-tuc');
	Route::get('bieu-mau','HomeController@BieuMau')->name('bỉeu-mau');
	Route::get('tai-lieu','HomeController@TaiLieu')->name('tai-lieu');
	Route::get('tin-tuc/{alias}','HomeController@Newsdetail')->name('tin-tuc-detail');
	Route::get('danh-muc-tin-tuc/{id}/{tenloai}','HomeController@DanhmucNews')->name('danh-muc-tin-tuc');
	Route::get('lien-he','HomeController@Lienhe')->name('lien-he');
	Route::post('lien-he','HomeController@PostLienhe');
	Route::get('faq-contact','HomeController@getFaqContact')->name('faq-contact');
	Route::post('faq-contact','HomeController@postFaqContact');
	Route::get('bang-gia','HomeController@BangGia')->name('bang-gia');

	Route::get('bang-gia-contact','HomeController@getBaoGiaContact')->name('bang-gia-contact');
	Route::post('bang-gia-contact','HomeController@postBaoGiaContact');
	
	Route::get('bang-gia/{alias}','HomeController@Banggiadetail')->name('bang-gia-detail');
	Route::get('bieu-mau','HomeController@Bieumau')->name('bieu-mau');
	Route::get('bieu-mau/{alias}','HomeController@Bieumaudetails')->name('bieu-mau-detail');
	Route::get('tai-lieu','HomeController@TaiLieu')->name('tai-lieu');
	Route::get('danh-muc-bieu-mau/{id}/{tenloai}','HomeController@CateDanhmucBieumau')->name('danh-muc-bieu-mau');
	Route::get('danh-muc-tai-lieu/{id}/{tenloai}','HomeController@CateDanhmucTaiLieu')->name('danh-muc-tai-lieu');
	Route::get('hoi-dap','HomeController@FAQ')->name('hoi-dap');
	Route::post('tim-kiem-hoi-dap','HomeController@timkiem_hoidap');
	Route::post('tim-kiem-bieu-mau','HomeController@timkiem_bieumau');
	Route::post('tim-kiem','HomeController@timkiem');
	
	Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('user.change-language');

});

Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
Route::get('logout','LoginController@getLogout')->name('getLogout');
Route::post('sign-in','LoginController@postLogin');

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu');

	Route::prefix('admin')->name('admin.')->group(function(){
		Route::get('index','AdminsController@index')->name('index');

		Route::get('add','AdminsController@create')->name('create');
		Route::post('add','AdminsController@store')->name('store');

		Route::get('edit/{id}','AdminsController@edit')->name('edit');
		Route::post('edit/{id}','AdminsController@update')->name('update');

		Route::get('change-password','AdminsController@Getchangepass')->name('changepass.update');
		Route::post('change-password','AdminsController@changepass')->name('postchangepass.update');

		Route::get('delete/{id}','AdminsController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::get('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('slider')->name('slider.')->group(function(){
		Route::get('index','SliderController@index')->name('index');

		Route::get('add','SliderController@create')->name('create');
		Route::post('add','SliderController@store')->name('store');

		Route::get('edit/{id}','SliderController@edit')->name('edit');
		Route::post('edit/{id}','SliderController@update')->name('update');

		Route::get('delete/{id}','SliderController@destroy')->name('destroy');
	});
	Route::prefix('lienhe')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');

		Route::get('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('hoidap')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');

		Route::get('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('nhanxet')->name('nhanxet.')->group(function(){
		Route::get('index','NhanXetController@index')->name('index');

		Route::get('add','NhanXetController@create')->name('create');
		Route::post('add','NhanXetController@store')->name('store');

		Route::get('edit/{id}','NhanXetController@edit')->name('edit');
		Route::post('edit/{id}','NhanXetController@update')->name('update');

		Route::get('delete/{id}','NhanXetController@destroy')->name('destroy');
	});
	Route::prefix('category-file')->name('category-file.')->group(function(){
		Route::get('index','CategoryFileController@index')->name('index');

		Route::get('add','CategoryFileController@create')->name('create');
		Route::post('add','CategoryFileController@store')->name('store');

		Route::get('edit/{id}','CategoryFileController@edit')->name('edit');
		Route::post('edit/{id}','CategoryFileController@update')->name('update');

		Route::get('delete/{id}','CategoryFileController@destroy')->name('destroy');
	});
	Route::prefix('file')->name('file.')->group(function(){
		Route::get('index','FileController@index')->name('index');
		Route::get('link-file','FileController@Linkfile')->name('link-file');

		Route::get('add','FileController@create')->name('create');
		Route::post('add','FileController@store')->name('store');

		Route::get('edit/{id}','FileController@edit')->name('edit');
		Route::post('edit/{id}','FileController@update')->name('update');

		Route::get('delete/{id}','FileController@destroy')->name('destroy');
	});
	Route::prefix('category')->name('category.')->group(function(){
		Route::get('index','CategoryController@index')->name('index');

		Route::get('add','CategoryController@create')->name('create');
		Route::post('add','CategoryController@store')->name('store');

		Route::get('edit/{id}','CategoryController@edit')->name('edit');
		Route::post('edit/{id}','CategoryController@update')->name('update');

		Route::get('delete/{id}','CategoryController@destroy')->name('destroy');
	});
	Route::prefix('news')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');

		Route::get('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('dichvu')->name('dichvu.')->group(function(){
		Route::get('index','ServiceController@index')->name('index');

		Route::get('add','ServiceController@create')->name('create');
		Route::post('add','ServiceController@store')->name('store');

		Route::get('edit/{id}','ServiceController@edit')->name('edit');
		Route::post('edit/{id}','ServiceController@update')->name('update');

		Route::get('delete/{id}','ServiceController@destroy')->name('destroy');
	});
	Route::prefix('banggia')->name('banggia.')->group(function(){
		Route::get('index','ListPriceController@index')->name('index');

		Route::get('add','ListPriceController@create')->name('create');
		Route::post('add','ListPriceController@store')->name('store');

		Route::get('edit/{id}','ListPriceController@edit')->name('edit');
		Route::post('edit/{id}','ListPriceController@update')->name('update');

		Route::get('delete/{id}','ListPriceController@destroy')->name('destroy');
	});
	Route::prefix('gioithieu')->name('introduce.')->group(function(){
		Route::get('index','IntroduceController@index')->name('index');
		Route::post('edit/{id}','IntroduceController@update')->name('update');
	});
	Route::prefix('logo')->name('logo.')->group(function(){
		Route::get('index','LogoController@index')->name('index');
		Route::post('edit/{id}','LogoController@update')->name('update');
	});
	Route::prefix('mangxahoi')->name('mangxahoi.')->group(function(){
		Route::get('index','SocialNetworkController@index')->name('index');
		Route::post('edit/{id}','SocialNetworkController@update')->name('update');
	});
	Route::prefix('googlemap')->name('googlemap.')->group(function(){
		Route::get('index','GoogleMapController@index')->name('index');
		Route::post('edit/{id}','GoogleMapController@update')->name('update');
	});
	Route::prefix('contactus')->name('contactus.')->group(function(){
		Route::get('index','ContactUsController@index')->name('index');
		Route::post('edit/{id}','ContactUsController@update')->name('update');
	});
	Route::prefix('footer')->name('footer.')->group(function(){
		Route::get('index','FooterController@index')->name('index');
		Route::post('edit/{id}','FooterController@update')->name('update');
	});
	Route::prefix('cauhinhkhac')->name('cauhinhkhac.')->group(function(){
		Route::get('index','ConfigurationController@index')->name('index');
		Route::post('edit/{id}','ConfigurationController@update')->name('update');
	});
	Route::prefix('faqcontact')->name('faqcontact.')->group(function(){
		Route::get('index','FAQContactController@index')->name('index');

		Route::get('add','FAQContactController@create')->name('create');
		Route::post('add','FAQContactController@store')->name('store');

		Route::get('edit/{id}','FAQContactController@edit')->name('edit');

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class Slider extends Model
{
    protected $table = "c1_slider";
    public $timestamp = false;
    public function dbSider()
    {
    	return DB::table('c1_slider');
    }
    public function listSlider()
    {
    	return $this->dbSider()->get()->toArray();
    }
    public function AddSlider($data)
    {
    	return $this->dbSider()->insert($data);
    }
    public function editSlider($id)
    {
    	return $this->dbSider()->find($id);
    }
    public function updateSlider($data,$id)
    {
    	return $this->dbSider()->whereId($id)->update($data);
    }
    public function delSlider($data)
    {
    	return $this->dbSider()->delete($data);
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\SliderRequest;
use App\Http\Controllers\Controller;
use App\Models\Slider;
use DateTime;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $slider;
    public function __construct(Slider $slider)
    {
        $this->sliders = $slider;
    }
    public function UpdateImage($id)
    {
        $item = $this->sliders->editSlider($id);
        $filename = 'public/uploads/slider'.$item->image;
        
        if(\File::exists($filename)){
            \File::delete($filename);
        }
    }
    public function index()
    {
        $data['slider'] = $this->sliders->listSlider();

        return view('admin.modules.slider.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.modules.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SliderRequest $request)
    {
        $data =array(
            'name'      => $request->name,
            'intro'     => $request->intro,
            'created_at'=> new DateTime
        );
        if($request->hasFile('image')){
                $image = $request->file('image');
                $image_name = time(). '-'.$image->getClientOriginalName();
                $des = 'public/uploads/slider';
                $image->move($des,$image_name);
                $data['image']=$image_name;
            }
        $insert = $this->sliders->AddSlider($data);
        if ( $insert) {
            return redirect()->route('slider.index')->with("success",'message.store_required');
        } else {
            return redirect()->back()->with('error','Thêm dữ liệu không thành công. Vui lòng thử lại');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['slider'] = $this->sliders->editSlider($id);

        return view('admin.modules.slider.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data =array(
            'name'      => $request->name,
            'intro'     => $request->intro,
            'created_at'=> new DateTime
        );
        if($request->hasFile('image')){
                $image = $request->file('image');
                $image_name = time(). '-'.$image->getClientOriginalName();
                $des = 'public/uploads/slider';
                $image->move($des,$image_name);
                $data['image']=$image_name;

                $this->UpdateImage($id);
            }

       $update =  $this->sliders->updateSlider($data,$id);
       if ($update) {
           return redirect()->route('slider.index')->with("success",'message.update_required');
       } else {

        return redirect()->back()->with('error','Cập nhật dữ liệu không thành công. Vui lòng thử lại');
       }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $data = $request->chk;

        for ($i=0; $i < count($data); $i++) { 
            $this->sliders->delSlider($data[$i]);
        }

        return redirect()->route('slider.index')->with("success",'message.delete_required');
    }
}

resources/views/admin/modules/slider/create.blade.php
@extends('admin.master')
@section('title','Thêm Slider')
@section('content')
@include('admin.blocks.alert')
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('slider.store')}}" method="POST" enctype="multipart/form-data">
            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.add_slider')}}</legend>

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.name_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="name" value="{{old('name')}}" class="form-control" />
                        </div>
                    </div>
                    <!-- /basic text input -->

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.intro_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <textarea rows="6" name="intro" class="form-control col-md-12 col-xs-12">{{old('intro')}}</textarea>
                        </div>
                    </div>
                    <!-- /basic text input -->

                    <!-- Styled file uploader -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.image_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="file" name="image" class="form-input-styled" >
                        </div>
                    </div>
                    <!-- /styled file uploader -->

                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.cancel')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.create')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/slider/edit.blade.php
@extends('admin.master')
@section('title','Chỉnh Sửa Slider')
@section('content')
@include('admin.blocks.alert')
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('slider.update',['id' => $slider->id])}}" method="POST" enctype="multipart/form-data">

            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.edit_slider')}}</legend>

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.name_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" name="name" class="form-control" value="{{ old('name',$slider->name) }}" />
                        </div>
                    </div>
                    <!-- /basic text input -->

                    <!-- Basic text input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.intro_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <textarea rows="6" name="intro" class="form-control col-md-12 col-xs-12">{{ old('intro',$slider->intro) }}</textarea>
                        </div>
                    </div>
                    <!-- /basic text input -->

                     <!-- Styled file uploader -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2"></label>
                        <div class="col-lg-6">
                             <img src="{{ asset('uploads/slider/'.$slider ->image)}}" width="75%">
                        </div>
                    </div>
                    <!-- /styled file uploader -->

                      <!-- Styled file uploader -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-2">{{trans('template.image_slider')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-6">
                            <input type="file" name="image" class="form-input-styled" >
                        </div>
                    </div>
                    <!-- /styled file uploader -->

                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.cancel')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.update')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/slider/index.blade.php
@extends('admin.master') 
@section('title','Danh Sách Slider') 
@section('content')
@include('admin.blocks.alert')
<div class="content">

    <!-- Page length options -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{trans('template.list_slider')}}</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <a href="{{route('slider.create')}}">
                <button type="button" class="btn btn-primary">Thêm Slider</button>
            </a>
        </div>
        <form action="{{route('slider.destroy',['action' => 'delete'])}}" />
            @method('DELETE')
            @csrf
        <table class="table datatable-show-all">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="chkall"  onClick="chkallClick(this);">
                    </th>
                    <th>Name</th>
                    <th>Banner</th>
                    <th>Mô Tả</th>
                    <th>Hoạt động</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
            	@foreach($slider as $item)
                <tr>
                    <td>
                        <input type="checkbox" name="chk[]" value="{{$item->id}}">
                    </td>
                    <td>{{$item->name}}</td>
                    <td>
                        <img src="{{asset('uploads/slider/'.$item ->image)}}" width="35%">
                    </td>
                    <td>{{$item->intro}}</td>
                    <td>{{ \Carbon\Carbon::createFromTimeStamp(strtotime($item ->created_at))->diffForHumans() }}</td>
                    <td class="text-center">
                        <a href="{{ route('slider.edit',['slider' => $item->id]) }}" class="list-icons-item text-primary-600" title="Sửa banner"><i class="icon-pencil7"></i></a> &nbsp;
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
            <button type="submit" class="btn btn-danger" onclick="return acceptDelete()" style="margin-left: 10px">{{trans('template.delete')}}</button><br/><br>              
        </form>  
    </div>
    <!-- /page length options -->
</div>
@endsection