routes/web.php
	Route::post('lien-he','HomeController@PostLienhe');
	Route::get('faq-contact','HomeController@getFaqContact')->name('faq-contact');
	Route::post('faq-contact','HomeController@postFaqContact');
	Route::get('bang-gia','HomeController@BangGia')->name('bang-gia');

	Route::get('bang-gia-contact','HomeController@getBaoGiaContact')->name('bang-gia-contact');
	Route::post('bang-gia-contact','HomeController@postBaoGiaContact');
	
	Route::get('bang-gia/{alias}','HomeController@Banggiadetail')->name('bang-gia-detail');
	Route::get('bieu-mau','HomeController@Bieumau')->name('bieu-mau');
	Route::get('bieu-mau/{alias}','HomeController@Bieumaudetails')->name('bieu-mau-detail');
	Route::get('tai-lieu','HomeController@TaiLieu')->name('tai-lieu');
	Route::get('danh-muc-bieu-mau/{id}/{tenloai}','HomeController@CateDanhmucBieumau')->name('danh-muc-bieu-mau');
	Route::get('danh-muc-tai-lieu/{id}/{tenloai}','HomeController@CateDanhmucTaiLieu')->name('danh-muc-tai-lieu');
	Route::get('hoi-dap','HomeController@FAQ')->name('hoi-dap');
	Route::post('tim-kiem-hoi-dap','HomeController@timkiem_hoidap');
	Route::post('tim-kiem-bieu-mau','HomeController@timkiem_bieumau');
	Route::post('tim-kiem','HomeController@timkiem');
	
	Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('user.change-language');

});

Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
Route::get('logout','LoginController@getLogout')->name('getLogout');
Route::post('sign-in','LoginController@postLogin');

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu');

	Route::prefix('admin')->name('admin.')->group(function(){
		Route::get('index','AdminsController@index')->name('index');

		Route::get('add','AdminsController@create')->name('create');
		Route::post('add','AdminsController@store')->name('store');

		Route::get('edit/{id}','AdminsController@edit')->name('edit');
		Route::post('edit/{id}','AdminsController@update')->name('update');

		Route::get('change-password','AdminsController@Getchangepass')->name('changepass.update');
		Route::post('change-password','AdminsController@changepass')->name('postchangepass.update');

		Route::get('delete/{id}','AdminsController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::get('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('slider')->name('slider.')->group(function(){
		Route::get('index','SliderController@index')->name('index');

		Route::get('add','SliderController@create')->name('create');
		Route::post('add','SliderController@store')->name('store');

		Route::get('edit/{id}','SliderController@edit')->name('edit');
		Route::post('edit/{id}','SliderController@update')->name('update');

		Route::get('delete/{id}','SliderController@destroy')->name('destroy');
	});
	Route::prefix('lienhe')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');

		Route::get('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('hoidap')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');

		Route::get('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('nhanxet')->name('nhanxet.')->group(function(){
		Route::get('index','NhanXetController@index')->name('index');

		Route::get('add','NhanXetController@create')->name('create');
		Route::post('add','NhanXetController@store')->name('store');

		Route::get('edit/{id}','NhanXetController@edit')->name('edit');
		Route::post('edit/{id}','NhanXetController@update')->name('update');

		Route::get('delete/{id}','NhanXetController@destroy')->name('destroy');
	});
	Route::prefix('category-file')->name('category-file.')->group(function(){
		Route::get('index','CategoryFileController@index')->name('index');

		Route::get('add','CategoryFileController@create')->name('create');
		Route::post('add','CategoryFileController@store')->name('store');

		Route::get('edit/{id}','CategoryFileController@edit')->name('edit');
		Route::post('edit/{id}','CategoryFileController@update')->name('update');

		Route::get('delete/{id}','CategoryFileController@destroy')->name('destroy');
	});
	Route::prefix('file')->name('file.')->group(function(){
		Route::get('index','FileController@index')->name('index');
		Route::get('link-file','FileController@Linkfile')->name('link-file');

		Route::get('add','FileController@create')->name('create');
		Route::post('add','FileController@store')->name('store');

		Route::get('edit/{id}','FileController@edit')->name('edit');
		Route::post('edit/{id}','FileController@update')->name('update');

		Route::get('delete/{id}','FileController@destroy')->name('destroy');
	});
	Route::prefix('category')->name('category.')->group(function(){
		Route::get('index','CategoryController@index')->name('index');

		Route::get('add','CategoryController@create')->name('create');
		Route::post('add','CategoryController@store')->name('store');

		Route::get('edit/{id}','CategoryController@edit')->name('edit');
		Route::post('edit/{id}','CategoryController@update')->name('update');

		Route::get('delete/{id}','CategoryController@destroy')->name('destroy');
	});
	Route::prefix('news')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');

		Route::get('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('dichvu')->name('dichvu.')->group(function(){
		Route::get('index','ServiceController@index')->name('index');

		Route::get('add','ServiceController@create')->name('create');
		Route::post('add','ServiceController@store')->name('store');

		Route::get('edit/{id}','ServiceController@edit')->name('edit');
		Route::post('edit/{id}','ServiceController@update')->name('update');

		Route::get('delete/{id}','ServiceController@destroy')->name('destroy');
	});
	Route::prefix('banggia')->name('banggia.')->group(function(){
		Route::get('index','ListPriceController@index')->name('index');

		Route::get('add','ListPriceController@create')->name('create');
		Route::post('add','ListPriceController@store')->name('store');

		Route::get('edit/{id}','ListPriceController@edit')->name('edit');
		Route::post('edit/{id}','ListPriceController@update')->name('update');

		Route::get('delete/{id}','ListPriceController@destroy')->name('destroy');
	});
	Route::prefix('gioithieu')->name('introduce.')->group(function(){
		Route::get('index','IntroduceController@index')->name('index');
		Route::post('edit/{id}','IntroduceController@update')->name('update');
	});
	Route::prefix('logo')->name('logo.')->group(function(){
		Route::get('index','LogoController@index')->name('index');
		Route::post('edit/{id}','LogoController@update')->name('update');
	});
	Route::prefix('mangxahoi')->name('mangxahoi.')->group(function(){
		Route::get('index','SocialNetworkController@index')->name('index');
		Route::post('edit/{id}','SocialNetworkController@update')->name('update');
	});
	Route::prefix('googlemap')->name('googlemap.')->group(function(){
		Route::get('index','GoogleMapController@index')->name('index');
		Route::post('edit/{id}','GoogleMapController@update')->name('update');
	});
	Route::prefix('contactus')->name('contactus.')->group(function(){
		Route::get('index','ContactUsController@index')->name('index');
		Route::post('edit/{id}','ContactUsController@update')->name('update');
	});
	Route::prefix('footer')->name('footer.')->group(function(){
		Route::get('index','FooterController@index')->name('index');
		Route::post('edit/{id}','FooterController@update')->name('update');
	});
	Route::prefix('cauhinhkhac')->name('cauhinhkhac.')->group(function(){
		Route::get('index','ConfigurationController@index')->name('index');
		Route::post('edit/{id}','ConfigurationController@update')->name('update');
	});
	Route::prefix('faqcontact')->name('faqcontact.')->group(function(){
		Route::get('index','FAQContactController@index')->name('index');

		Route::get('add','FAQContactController@create')->name('create');
		Route::post('add','FAQContactController@store')->name('store');

		Route::get('edit/{id}','FAQContactController@edit')->name('edit');
		Route::post('edit/{id}','FAQContactController@update')->name('update');

		Route::get('delete/{id}','FAQContactController@destroy')->name('destroy');
	});
	Route::prefix('baogiacontact')->name('baogiacontact.')->group(function(){
		Route::get('index','BaoGiaContactController@index')->name('index');

		Route::get('add','BaoGiaContactController@create')->name('create');
		Route::post('add','BaoGiaContactController@store')->name('store');

		Route::get('edit/{id}','BaoGiaContactController@edit')->name('edit');
		Route::post('edit/{id}','BaoGiaContactController@update')->name('update');

app/Models/ContactUs.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class ContactUs extends Model
{
    protected $table = 'c1_config';
    public $timestamp = false;
    public function dbContactsUs()
    {
    	return DB::table('c1_config');
    }
  	public function editContactUs($id)
  	{
  		return $this->dbContactsUs()->select('content','name_phone')->find($id);
  	}
    public function updateHotLine1($data)
    {
      return $this->dbContactsUs()->whereId(6)->update($data);
    }
     public function updatePhoneName1($data)
    {
      return $this->dbContactsUs()->whereId(6)->update($data);
    }
    public function updateHotLine2($data)
    {
      return $this->dbContactsUs()->whereId(7)->update($data);
    }
    public function updatePhoneName2($data)
    {
      return $this->dbContactsUs()->whereId(7)->update($data);
    }
    public function updateHotLine3($data)
    {
      return $this->dbContactsUs()->whereId(8)->update($data);
    }
    public function updatePhoneName3($data)
    {
      return $this->dbContactsUs()->whereId(8)->update($data);
    }
}

app/Http/Controllers/Admin/ContactUsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ContactUs;
use DateTime;

class ContactUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $contactus;
    public function __construct(ContactUs $contactus)
    {
        $this->contactus =$contactus;
    }
    public function index()
    {
        $data['hotline1'] = $this->contactus->editContactUs(6);
        $data['phonename1'] = $this->contactus->editContactUs(6);

        $data['hotline2'] = $this->contactus->editContactUs(7);
        $data['phonename2'] = $this->contactus->editContactUs(7);

        $data['hotline3'] = $this->contactus->editContactUs(8);
        $data['phonename3'] = $this->contactus->editContactUs(8);
       

        return view('admin.modules.contactus.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.modules.contactus.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.modules.contactus.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //$this->contactus->updateContactUs(['content' => $request->Lienhe]);
        $this->contactus->updateHotLine1(['content' => $request->HotLine1]);
        $this->contactus->updatePhoneName1(['name_phone' => $request->PhoneName1]);

        $this->contactus->updateHotLine2(['content' => $request->HotLine2]);
        $this->contactus->updatePhoneName2(['name_phone' => $request->PhoneName2]);

        $this->contactus->updateHotLine3(['content' => $request->HotLine3]);
        $this->contactus->updatePhoneName3(['name_phone' => $request->PhoneName3]);

        return redirect()->route('contactus.index')->with("success",'message.update_required');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
    }
}

resources/views/admin/modules/contactus/index.blade.php
@extends('admin.master')
@section('title','Liên Hệ Chúng Tôi')
@section('content')
@include('admin.blocks.alert')
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('contactus.update',['action' => 'id'])}}" method="POST" enctype="multipart/form-data">
            	@csrf
                <fieldset class="mb-3">
                    <center>
                        <legend class="text-uppercase font-size-lg font-weight-bold">Liên Hệ</legend>
                    </center>
                     <!-- Basic hotline1 input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.hotline')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="HotLine1" class="form-control" value="{{$hotline1->content}}" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.phone_name')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="PhoneName1" class="form-control" value="{{$phonename1->name_phone}}" placeholder="Your Name" />
                        </div>
                    </div>
                    <!-- /basic hotline1 input -->

                     <!-- Basic hotline2 input -->
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.hotline')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="HotLine2" class="form-control" value="{{$hotline2->content}}" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.phone_name')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="PhoneName2" class="form-control" value="{{$phonename2->name_phone}}" placeholder="Your Name" />
                        </div>
                    </div>
                    <!-- /basic hotline2 input -->

                     <!-- Basic hotline3 input -->
                   <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.hotline')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="HotLine3" class="form-control" value="{{$hotline3->content}}" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">{{trans('template.phone_name')}}<span class="text-danger">*</span></label>
                        <div class="col-lg-3">
                            <input type="text" name="PhoneName3" class="form-control" value="{{$phonename3->name_phone}}" placeholder="Your Name" />
                        </div>
                    </div>
                    <!-- /basic hotline3 input -->

                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.cancel')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.update')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection